var g_fromwelcome=document.location.href.indexOf("?fromwelcome=1")!=-1,g_results=null;function onLoad(){populate()}
function populate(){var a=getBG();if(a.have_nplastpass(true)&&typeof a.g_nplastpass.get_chrome_passwords=="function")g_results=a.g_nplastpass.get_chrome_passwords();else document.getElementById("needbinaryspan").style.display="";var b=[];for(a=0;a<g_results.length;a++)if(typeof g_results[a].username!="undefined"&&g_results[a].username!=""||typeof g_results[a].password!="undefined"&&g_results[a].password!="")b[b.length]=g_results[a];g_results=b;b=[];event_handlers={};for(a in g_results)b.push(getsitehtml(g_results,
a));b.push('<div id="gridclear" class="clear"/>');document.getElementById("gridsite").innerHTML=b.join("");for(a in event_handlers)document.getElementById(a).addEventListener("click",event_handlers[a])}function sp(a,b){a.innerHTML=a.innerHTML==gs("Show")?g_results[b].password:gs("Show")}var MAX_SITENAME_LEN=30,MAX_SITEUSERNAME_LEN=15;
function getsitehtml(a,b){id=b;name=trunc(a[b].url,MAX_SITENAME_LEN);username=typeof a[b].username!="undefined"?trunc(a[b].username,MAX_SITEUSERNAME_LEN):"";event_handlers["link"+id]=function(){sp(this,this.id.substring(4))};return'<div class="site" id="site'+id+'"><div class="border"><div class="sitename"><span class="content">'+name+'</span></div><div class="siteusername"><span class="content">'+username+'</span></div><div class="sitepassword"><span class="content"><a id="link'+id+'" href="#">'+
gs("Show")+'</a></span></div><div class="siteimport"><input type="checkbox" id="import'+id+'" checked></div></div></div>'}function trunc(a,b){if(a.length<=b)return a;return a.substr(0,b)+"..."}function select_all(){for(var a=0;a<g_results.length;a++)document.getElementById("import"+a).checked=true}function unselect_all(){for(var a=0;a<g_results.length;a++)document.getElementById("import"+a).checked=false}
function checkdup(a,b){if(a.url=="http://sn")return false;var c=getBG().getsites(b),e;for(e in c){var d=getBG().g_sites[e];if(d&&d.unencryptedUsername==a.username&&getBG().lpmdec_acct(d.password,true,d,getBG().g_shares)==a.password)return true}return false}
function lpimport(){for(var a=[],b="cmd=uploadaccounts&username="+getBG().en(getBG().g_username),c=0,e=0;e<g_results.length;e++)if(document.getElementById("import"+e).checked){var d=g_results[e],f=getname_url(d.url);if(!checkdup(d,lp_gettld_url(d.url))){b+="&url"+c+"="+getBG().en(getBG().bin2hex(punycode.URLToASCII(d.url)));b+="&username"+c+"="+getBG().en(getBG().lpenc(d.username));b+="&password"+c+"="+getBG().en(getBG().lpenc(d.password));b+="&type"+c+"=ie";b+="&usernamefield"+c+"="+getBG().en(d.username_field);
b+="&passwordfield"+c+"="+getBG().en("*"+d.password_field);for(var g,h=1;h<=1E3;h++){g=f;if(h>1)g+=" ("+h+")";if(!lp_in_array(g,a)){a[a.length]=g;break}}b+="&name"+c+"="+getBG().en(getBG().lpenc(g));c++;getBG().LPISLOC&&lpImportChromePasswordLocal(d)}}if(getBG().LPISLOC){getBG().g_local_accts_version++;getBG().rewritelocalfile()}b+=getBG().get_identity_param();getBG().lpMakeRequest(base_url+"lastpass/api.php",b,lpUploadAccountsResponse)}
function lpImportChromePasswordLocal(a){var b=getBG(),c=b.createNewAcct();c.aid=get_new_id();c.name=lp_gettld_url(a.url);c.url=a.url;var e=lp_gettld_url(c.url);c.tld=e;c.unencryptedUsername=a.username;c.username=b.lpmenc(a.username,true);c.password=b.lpmenc(a.password,true);var d=get_new_id();c.urid=d;addfield(c,a.username_field,"text",b.lpmenc(a.username,true),d);addfield(c,a.password_field,"password",b.lpmenc(a.password,true),d);if(typeof b.g_tlds[c.tld]=="undefined")b.g_tlds[c.tld]=[];b.g_tlds[c.tld][c.aid]=
true;b.add_ident_aid(c.aid);if(typeof b.g_equivalentdomains[e]!="undefined"){a=b.g_equivalentdomains[e];if(typeof b.g_equivalentdomains[a]!="undefined")for(e=0;e<b.g_equivalentdomains[a].length;e++){d=b.g_equivalentdomains[a][e];if(typeof b.g_tlds[d]=="undefined")b.g_tlds[d]=[];b.g_tlds[d][aid]=true}}b.g_sites[c.aid]=c}function addfield(a,b,c,e,d){var f={};f.otherfield=false;f.name=b;f.type=c;f.value=e;f.formname="";f.checked=false;f.urid=d;f.otherlogin="0";f.url="";a.fields[a.fields.length]=f}
function lpUploadAccountsResponse(a){if(a)if(a.readyState==4)if(a.status==200)if(a.responseText.indexOf("OK")>0){getBG().get_accts();getBG().refresh_windows();alert(gs("Your Google Chrome passwords have been imported successfully."));g_fromwelcome?redirect_to_url("configure_formfill.html"):getBG().closecurrenttab("import.html")}else alert(gs("An error occurred while importing your Google Chrome passwords."))}
function cancel(){g_fromwelcome?redirect_to_url("configure_formfill.html"):getBG().closecurrenttab("import.html")}function getbinary(){var a=getBG();a&&a.install_binary();setTimeout(function(){window.close()},0)};
