var reprompt_callback=null,reprompt_error_callback=null;g_fixpbkdf2=!0;
function do_submit(){var a=fix_username(document.getElementById("u").value),f=document.getElementById("p").value;document.getElementById("p").value="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";var b=get_key_iterations(a);getBG().make_lp_key_hash_iterations(a,f,b,function(b,j){document.getElementById("p").blur();if(null!=reprompt_callback){var e=getBG();if(b==e.g_local_key){var h=0;document.getElementById("donotrepromptfor").checked&&(h=document.getElementById("donotrepromptforsecs").value);
e.lpPutUserPref("reprompttime",h);e.lpWriteAllPrefs();e.set_last_reprompt_time();reprompt_error_callback=null;e.select_selectedtabid();reprompt_callback();setTimeout(function(){window.close()},0)}else alert(gs("Invalid Password.")),setTimeout(function(){closePop()},0)}else(e=getBG())?(document.getElementById("rememberpassword").checked||(document.getElementById("p").value=""),e.g_manual_login=!0,e.LP_do_login(a,f,document.getElementById("rememberemail").checked,document.getElementById("rememberpassword").checked,
null,document.getElementById("showvault").checked,b,j),reprompt_error_callback=null,f="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",setTimeout(function(){closePop()},0)):alert(gs("Can't find hidden LastPass window"))});return!1}var passwords=[];
function load(a){try{var f="undefined"!=typeof chrome&&"undefined"!=typeof chrome.extension;if(!f&&!a&&("undefined"==typeof safari||"undefined"==typeof safari.extension.globalPage))get_data("login",function(){load(!0)});else{getBG().LPISLOC&&(document.getElementById("forgotcontainer").style.display=document.getElementById("screenkeyboardcontainer").style.display=document.getElementById("createaccountcontainer").style.display="none");getBG().g_hidecreate&&(document.getElementById("createaccountcontainer").style.display=
"none");if(getBG().g_hidevault||getBG().g_hideshowvault)document.getElementById("showvaultrow").style.display="none";getBG().g_hidescreenkeyboard&&(document.getElementById("screenkeyboardcontainer").style.display="none");var b=getBG();can_chrome_do_math()||b.openURL(getchromeurl("mathfail.html"));if(null!=b.g_reprompt_callback){reprompt_callback=b.g_reprompt_callback;b.g_reprompt_callback=null;reprompt_error_callback=b.g_reprompt_error_callback;b.g_reprompt_error_callback=null;document.getElementById("reprompttext").style.display=
"";document.getElementById("deleteicon").style.display="none";document.getElementById("rememberemailrow").style.display="none";document.getElementById("rememberpasswordrow").style.display="none";document.getElementById("showvaultrow").style.display="none";document.getElementById("donotrepromptforrow").style.display="";document.getElementById("u").value=b.g_username;document.getElementById("u").disabled=!0;var k=b.lpGetPref("reprompttime",0);document.getElementById("donotrepromptfor").checked=0<k;
document.getElementById("donotrepromptforsecs").value=k;document.getElementById("p").focus();document.getElementById("links").style.display="none";setTimeout(function(){document.getElementById("p").focus()},50)}else{var j=b.lpGetPref("rememberemail",1),e=b.lpGetPref("rememberpassword",-1),h=b.lpGetPref("showvault",-1);document.getElementById("rememberemail").checked=1==j?!0:!1;document.getElementById("rememberpassword").checked=1==e?!0:!1;document.getElementById("showvault").checked=1==h?!0:!1;getBG().g_db_transaction_tested=
getBG().g_db_transaction_worked=!1;var g=opendb();g||(g=opendb());createSavedLoginsTable(g);g?(g.transaction(function(a){getBG().g_db_transaction_tested=getBG().g_db_transaction_worked=!0;a.executeSql("SELECT * FROM LastPassSavedLogins2 order by last_login desc",[],function(a,b){for(var c=[],d=0;d<b.rows.length;d++)c[d]=b.rows.item(d).username,passwords[c[d]]=b.rows.item(d).password,1==b.rows.item(d)["protected"]?passwords[c[d]]=getBG().unprotect_data(passwords[c[d]]):2==b.rows.item(d)["protected"]&&
(passwords[c[d]]=lpdec(passwords[c[d]],AES.hex2bin(SHA256(c[d]))));c.sort(function(a,b){return a.toLowerCase()<b.toLowerCase()?-1:1});create_combo("u",c);c="";d=document.location.href.indexOf("sesameusername=");-1!=d&&(c=document.location.href.substr(d+15),d=c.indexOf("&"),-1!=d&&(c=c.substring(0,d)),c=decodeURIComponent(c));0<b.rows.length||""!=c?(c=""!=c?c:b.rows.item(0).username,d="undefined"!=typeof passwords[c]?passwords[c]:"",document.getElementById("u").value=c,document.getElementById("p").focus(),
""!=d&&(document.getElementById("p").value=d,-1==e&&(document.getElementById("rememberpassword").checked=!0),document.getElementById("login").focus())):document.getElementById("u").focus()},function(a,b){console_log(b)})}),f&&(-1!=navigator.userAgent.indexOf("Chrome/4")||-1!=navigator.userAgent.indexOf("Chrome/5"))&&setTimeout(function(){test_db_failed(1)},5E3)):test_db_failed(0)}}}catch(l){console_log(l.message)}}window.addEventListener("keydown",function(a){handle_keydown(a)},!1);
function handle_keydown(a){if(68==(0!=a.keyCode?a.keyCode:a.charCode)&&a.ctrlKey)document.body.innerHTML="<pre>"+getBG().g_console_log+"</pre>",a.cancelBubble=!0,a.preventDefault(),a.stopPropagation()}function test_db_failed(a){L("test_db_failed timeout: "+a);getBG().g_db_transaction_tested=!0;getBG().g_db_transaction_worked||(document.getElementById("u").focus(),create_combo("u",[]))}
function username_changed(){var a=document.getElementById("u").value;"undefined"!=typeof passwords[a]&&""!=passwords[a]?(document.getElementById("p").value=passwords[a],document.getElementById("rememberpassword").checked=!0):(document.getElementById("p").value="",document.getElementById("rememberpassword").checked=!1)}
function delete_user(){var a=document.getElementById("u").value,f=opendb();createSavedLoginsTable(f);f&&f.transaction(function(b){b.executeSql("DELETE FROM LastPassSavedLogins2 WHERE username=?",[a])},function(){},function(a,b){console_log(b)});delete passwords[a];delete_combo_item("u",a);document.getElementById("u").value="";for(var b in passwords){document.getElementById("u").value=b;break}username_changed()}function retsubmit(a){return 13==a.keyCode?(do_submit(),!1):!0}
function glow(a){a.className+=" glow"}function dim(a){a.className=a.className.replace(/\bglow\b/,"")}function closePop(){"undefined"!=typeof chrome&&"undefined"!=typeof chrome.extension&&parent?parent.window_close():g_ismaxthon?setTimeout(function(){window.external.mxGetRuntime().getActionByName("lppanel").hide()},0):getBG().closePop()}function oninitlogin(){}
function onshowlogin(){parent.body&&(parent.body.style.margin="0px");-1==location.search.indexOf("foo")&&(location.href="lp_toolstrip.html?browseraction=1&foo")}function onhidelogin(){parent.body&&(parent.body.style.margin="8px")};
