var yubikeysubmit=!1;function oninityubikey(){}function onshowyubikey(){document.getElementById("yubikeyotp").value="";setTimeout(function(){window.focus()},0);setTimeout(function(){document.getElementById("yubikeyotp").focus()},0);setTimeout(function(){document.getElementById("yubikeyotp").focus()},100);yubikeysubmit=!1;sendBG({cmd:"turnofficon"})}function onhideyubikey(){yubikeysubmit||sendBG({cmd:"yubikeyauth",otp:""});closemole()}
function otpcheck(){var a="";if(document.getElementById("lptrustyubi").checked&&(a=document.getElementById("yubitrustlabel").value,""==a)){document.getElementById("labelyubi").style.color="red";return}var b=document.getElementById("yubikeyotp").value;""!=b&&(yubikeysubmit=!0,document.getElementById("yubikeyotp").blur(),sendBG({cmd:"yubikeyauth",otp:b,label:a}));onhideyubikey()}function lostkey(){sendBG({cmd:"lostkey"});closemole()}var googleauthsubmit=!1;function oninitgoogleauth(){}
function onshowgoogleauth(){document.getElementById("googleauthotp").value="";setTimeout(function(){window.focus()},0);setTimeout(function(){document.getElementById("googleauthotp").focus()},0);setTimeout(function(){document.getElementById("googleauthotp").focus()},100);googleauthsubmit=!1;sendBG({cmd:"turnofficon"})}function onhidegoogleauth(){googleauthsubmit||sendBG({cmd:"googleauthauth",otp:""});closemole()}
function googleauthotpcheck(){var a="";if(document.getElementById("lptrustgoogleauth").checked&&(a=document.getElementById("googleauthtrustlabel").value,""==a)){document.getElementById("labelgoogleauth").style.color="red";return}var b=document.getElementById("googleauthotp").value;""!=b&&(googleauthsubmit=!0,sendBG({cmd:"googleauthauth",otp:b,label:a}));onhidegoogleauth()}function googleauthlostkey(){sendBG({cmd:"googleauthlostkey"});closemole()}var outofbandsubmit=!1;
function oninitoutofband(){}var g_trustlabel="";
function onshowoutofband(){setTimeout(function(){window.focus()},0);outofbandsubmit=!1;sendBG({cmd:"turnofficon"});"1"==getQueryVariable("allowtrust")&&(document.getElementById("outofbandtrustdiv").style.display="");sendBG({cmd:"outofbandauth",otp:"dummy"});setInterval(function(){var a=document.getElementById("lptrustoutofband").checked?document.getElementById("outofbandtrustlabel").value:"";a!=g_trustlabel&&(g_trustlabel=a,sendBG({cmd:"settrustlabel",trustlabel:a}))},100)}
function onhideoutofband(){outofbandsubmit||sendBG({cmd:"outofbandauth",otp:""});closemole()}function outofbandlostkey(){sendBG({cmd:"outofbandlostkey"});closemole()}var securityquestionsubmit=!1;function oninitsecurityquestion(){}
function onshowsecurityquestion(){document.getElementById("securityquestionotp").value="";setTimeout(function(){window.focus()},0);setTimeout(function(){document.getElementById("securityquestionotp").focus()},0);setTimeout(function(){document.getElementById("securityquestionotp").focus()},100);securityquestionsubmit=!1;sendBG({cmd:"turnofficon"});document.getElementById("_docwrite_lp_toolstrip55").innerHTML=of(getQueryVariable("question"));getQueryVariable("autotrust")&&(document.getElementById("lptrustsecurityquestion").style.display=
"none",document.getElementById("_docwrite_lp_toolstrip56").style.display="none",document.getElementById("lptrustsecurityquestion").checked=!0,document.getElementById("securityquestiontrustlabel").value=(g_ischrome?gs("Chrome"):g_issafari?gs("Safari"):g_isopera?gs("Opera"):g_ismaxthon?gs("Maxthon"):gs("Unknown"))+" - "+getQueryVariable("uuid"));"1"==getQueryVariable("hidedisable")&&(document.getElementById("securityquestionlostkey").style.display="none")}
function onhidesecurityquestion(){securityquestionsubmit||sendBG({cmd:"securityquestionauth",otp:""});closemole()}
function securityquestionotpcheck(){var a="";if(document.getElementById("lptrustsecurityquestion").checked&&(a=document.getElementById("securityquestiontrustlabel").value,""==a)){document.getElementById("labelsecurityquestion").style.color="red";return}var b=document.getElementById("securityquestionotp").value;""!=b&&(securityquestionsubmit=!0,sendBG({cmd:"securityquestionauth",otp:b,label:a}));onhidesecurityquestion()}
function securityquestionlostkey(){sendBG({cmd:"securityquestionlostkey"});closemole()}var sesamesubmit=!1;function oninitsesame(){}function onshowsesame(){document.getElementById("sesameotplocal").value="";setTimeout(function(){window.focus()},0);setTimeout(function(){document.getElementById("sesameotplocal").focus()},0);setTimeout(function(){document.getElementById("sesameotplocal").focus()},100);sesamesubmit=!1;sendBG({cmd:"turnofficon"})}
function onhidesesame(){sesamesubmit||sendBG({cmd:"sesameauth",otp:""});closemole()}function sesameotpcheck(){var a="";if(document.getElementById("lptrustsesame").checked&&(a=document.getElementById("sesametrustlabel").value,""==a)){document.getElementById("labelsesame").style.color="red";return}var b=document.getElementById("sesameotplocal").value;""!=b&&(sesamesubmit=!0,sendBG({cmd:"sesameauth",otp:b,label:a}));onhidesesame()}function sesamelostkey(){sendBG({cmd:"sesamelostkey"});closemole()}
var gridsubmit=!1;function oninitgrid(){}
function onshowgrid(){document.getElementById("lpgridinput1").value="";document.getElementById("lpgridinput2").value="";document.getElementById("lpgridinput3").value="";document.getElementById("lpgridinput4").value="";sendBG({cmd:"turnofficon"});var a=document.location.href,a=a.substr(a.indexOf("challenge=")+10),b=a.indexOf("&");-1!=b&&(a=a.substring(0,b));for(var a=decodeURIComponent(a),a=a.replace(/^\s+|\s+$/g,""),b=a.split(" "),c=0;c<b.length;c++)document.getElementById("grid"+(c+1)+"label").innerHTML=
b[c];console_log(a);setTimeout(function(){window.focus()},0);setTimeout(function(){document.getElementById("lpgridinput1").focus()},0);setTimeout(function(){document.getElementById("lpgridinput1").focus()},100);gridsubmit=!1}function onhidegrid(){gridsubmit||sendBG({cmd:"gridauth",gridvalues:""});closemole()}
function gridcheck(){var a="";if(document.getElementById("lptrustgrid").checked&&(a=document.getElementById("gridtrustlabel").value,""==a)){document.getElementById("labelgrid").style.color="red";return}var b="";""!=document.getElementById("lpgridinput1").value&&(""!=document.getElementById("lpgridinput2").value&&""!=document.getElementById("lpgridinput3").value&&""!=document.getElementById("lpgridinput4").value)&&(b=document.getElementById("lpgridinput1").value+","+document.getElementById("lpgridinput2").value+
","+document.getElementById("lpgridinput3").value+","+document.getElementById("lpgridinput4").value);""!=b&&(gridsubmit=!0,sendBG({cmd:"gridauth",gridvalues:b,label:a}));onhidegrid()}function lostgrid(){sendBG({cmd:"gridlostkey"});closemole()};
