function upload_rsa_keys(a,b,c){if(lploggedin){var e="",d="";d="";if(!b){e=typeof a.publickey!="undefined"?a.publickey:encode_public_key(a);d="LastPassPrivateKey<"+(typeof a.privatekey!="undefined"?a.privatekey:encode_private_key(a))+">LastPassPrivateKey";d=AES.bin2hex(atob(AES.Encrypt({pass:g_local_key+g_local_key.substring(0,16),data:d,b64:true,bits:256,mode:"cbc"}))).toUpperCase()}a=g_local_key;c="";if(a!=null&&a!=""){c=AES.bin2hex(a);c=c.toUpperCase()}a=c==""?"":SHA256(c);b=c==""?"":SHA256(d);
c=typeof forcewriteprivatearg=="undefined"||forcewriteprivatearg==0?0:forcewriteprivatearg;d="privatekeyenc="+LP.en(d);d+="&publickey="+LP.en(e);d+="&forcewriteprivate="+LP.en(c);d+="&userkeyhexhash="+LP.en(a);d+="&privatekeyenchexhash="+LP.en(b);d+="&from="+LP.en("crplugin");lpMakeRequest(base_url+"uploadrsakeys.php",d,upload_rsa_keys_response,null)}}
function upload_rsa_keys_response(a){if(a.readyState==4&&a.status==200&&a.responseXML&&a.responseXML.documentElement){a=a.responseXML.documentElement.getElementsByTagName("ok");var b="";if(a.length>0){b=a[0].getAttribute("privatekeyenchex");if(b!=null&&b!=""){writersaprivatekeyenchextodb(b);readrsaprivatekeyhexfromdb(true,null,null,function(){if(g_shares&&g_shares.length>0){console_log("upload_rsa_keys_response found shares: reparse!");get_accts_local(true,"refetchsharing")}})}}}}
function writersaprivatekeyenchextodb(a){if(!(g_username==null||g_username=="")){console_log("writersaprivatekeyenchextodb");lpSaveData(a,"rsakey")}}
function readrsaprivatekeyhexfromdb(a,b,c,e){if(!g_nosharingkeys)if(!(g_username==null||g_username==""||g_local_key==null))if((typeof a=="undefined"||!a)&&lp_rsaprivatekeyhex!=""&&(!c||SHA256(lp_rsaprivatekeyenchex)==c))e&&e(lp_rsaprivatekeyhex);else{rsa_clearvars();a=opendb();createDataTable(a);a&&a.transaction(function(d){d.executeSql("SELECT * FROM LastPassData WHERE username_hash=? AND type=?",[db_prepend(g_username_hash),"rsakey"],function(f,h){if(h.rows.length>0){var g=h.rows.item(0).data;if(g==
""||g==null)DeleteFromDB("rsakey");else if(c&&SHA256(g)!=c){console_warn("RSA Hashes didn't match. Deleting local!");DeleteFromDB("rsakey");if(g_privkeyattempts==0){g_privkeyattempts=1;setTimeout(function(){console.error("BAH!!!");upload_rsa_keys(null,true)},500)}}else{var i=AES.Decrypt({pass:g_local_key+g_local_key.substring(0,16),data:btoa(AES.hex2bin(g)),b64:true,bits:256,mode:"cbc"}),j=rsa_extractprivatekey(i);if(j==null){console_warn("failed to extract rsa key from file "+j);lpReportError("readrsaprivatekeyhexfromfile : failed to extract rsa key from file - did we change our password on another PC? datahex.length="+
g.length+" decryptedbin.length="+i.length);DeleteFromDB("rsakey")}else{console_log("readrsaprivatekeyhexfromfile : all is good!");lp_rsaprivatekeyenchex=g;lp_rsaprivatekeyhex=j;lp_rsaprivatekeyenchexserverhash=SHA256(lp_rsaprivatekeyenchex);e&&e(lp_rsaprivatekeyhex);if(g_shares&&g_shares.length==1&&g_shares[0].id==0){console_log("Shared folder found, we just got the key, reparse!");get_accts_local()}}}}else b&&upload_rsa_keys(null,true)},function(f,h){console_log(h)})})}}
function rsa_extractprivatekey(a){if(a.length<=38){lpReportError("rsa_extractprivatekey : failed to extract rsaprivatekeyhex : length="+a.length+" is too short");return null}if(a.indexOf("LastPassPrivateKey<")!=0){lpReportError("rsa_extractprivatekey : failed to extract rsaprivatekeyhex : expected_prefix='LastPassPrivateKey<'   actual_prefix='"+a.substring(0,19)+"'");return null}var b=a.indexOf(">LastPassPrivateKey");if(b!=a.length-19){lpReportError("rsa_extractprivatekey : failed to extract rsaprivatekeyhex : expected_prefix='LastPassPrivateKey<'   actual_prefix='"+
a.substring(0,19)+"'");return null}a=a.substring(19,b);if(a.length<2E3){lpReportError("rsa_extractprivatekey : failed to extract rsaprivatekeyhex : we expect a length of approx 2426    actual_length="+a.length);return null}return a}function rsa_userchangedpassword(){console_log("rsa_userchangedpassword : called");DeleteFromDB("rsakey");rsa_clearvars()}function rsa_clearvars(){lp_rsaprivatekeyenchexserverhash=lp_rsaprivatekeyenchex=lp_rsaprivatekeyhex=""}var lppendingsharests=0;
function rsa_setpendingsharests(a){lppendingsharests=typeof a!="undefined"&&a?0:(new Date).getTime()}
function rsa_acceptpendingshares(a){if(!(!lploggedin||lploggedinoffline||g_local_key==null))if(lp_rsaprivatekeyhex!=""){rsaprivatekeyhex=lp_rsaprivatekeyhex;if(g_pendings.length!=0)if((new Date).getTime()-lppendingsharests<1E4)console_log("lprsa_acceptpendingshares : skipping because we were already called very recently");else{rsa_setpendingsharests();a=[];for(var b in g_pendings){var c=g_pendings[b];if(c.shareautoaccept==1){var e="";e="";if(have_nplastpass()&&typeof g_nplastpass.xCryptoRSADecrypt==
"function"){e=g_nplastpass.xCryptoRSADecrypt(rsaprivatekeyhex,c.sharekeyenchex);e=AES.hex2bin(e)}else{e=new RSAKey;if(!parse_private_key(e,lp_rsaprivatekeyhex)){console_error("Private key could not be parsed while auto accepting shares");return}e=e.decrypt(c.sharekeyenchex);AES.bin2hex(e)}if(e==""){console_error("Share key bin empty while auto accepting shares");return}var d=dec(c.sharename,e),f=dec(c.sharegroup,e),h=dec(c.username,e),g=dec(c.password,e),i=dec(c.extra,e),j=true,k={};for(b in c.shareafids){k[b]=
dec(c.shareafids[b],e);if(c.shareafids[b]!=""&&k[b]==""){j=false;break}}if(c.sharename!=""&&d==""||c.sharegroup!=""&&f==""||c.username!=""&&h==""||c.password!=""&&g==""||c.extra!=""&&i==""||!j)lpReportError("lprsa_acceptpendingshares : failing autoaccept of share because we failed to decrypt at least one value");else{var l=lpenc(d),m=lpenc(f),n=lpenc(h),o=lpenc(g),p=lpenc(i);j=true;e={};for(b in k){e[b]=lpenc(k[b]);if(k[b]!=""&&e[b]==""){j=false;break}}if(d!=""&&l==""||f!=""&&m==""||h!=""&&n==""||
g!=""&&o==""||i!=""&&p==""||!j)lpReportError("lprsa_acceptpendingshares : failing autoaccept of share because we failed to reencrypt at least one value");else{c={aid:c.id,name:l,group:m,username:n,password:o,extra:p};d=0;for(b in e){c["afid"+d]=b;c["afidv"+d]=e[b];++d}c.numafids=d;a.push(c)}}}}if(a.length>0){c="cmd="+LP.en("autoacceptshares")+"&from="+LP.en("crplugin")+"&numshares="+LP.en(a.length);e=0;for(b in a){d="&share"+e;++e;for(var q in a[b])c+=d+q+"="+LP.en(a[b][q])}console_log("rsa_acceptpendingshares : issuing server request to autoaccept "+
a.length+" shares");lpMakeRequest(base_url+"showacceptshare.php",c,rsa_acceptpendingsharesresponse)}else console_log("rsa_acceptpendingshares : no shares to autoaccept so not issuing server request")}}else a||readrsaprivatekeyhexfromdb(false,null,null,rsa_acceptpendingshares)}
function rsa_acceptpendingsharesresponse(a){if(a.readyState==4){console_log("rsa_acceptpendingsharesresponse : received response from server");if(a.status!=200)lpReportError("lprsa_acceptpendingsharesresponse : request failed status="+a.status);else if(a.responseXML==null||a.responseXML.documentElement==null)lpReportError("lprsa_acceptpendingsharesresponse : request failed xml invalid A text="+a.responseText);else{var b=a.responseXML.documentElement.getElementsByTagName("ok");!b||b.length==0?lpReportError("lprsa_acceptpendingsharesresponse : request failed xml invalid B text="+
a.responseText):get_accts()}}}function rsa_setshareeautopushests(a){g_shareeautopushests=typeof a!="undefined"&&a?0:(new Date).getTime()}function rsa_acceptshareeautopushes(){var a=false,b;for(b in g_shareeautopushes){a=true;break}if(a)if(!(!lploggedin||lploggedinoffline||g_local_key==null))if(!((new Date).getTime()-lpshareeautopushests<1E4)){rsa_setshareeautopushests();readrsaprivatekeyhexfromdb(false,null,null,rsa_acceptshareeautopushes2)}}
function rsa_acceptshareeautopushes2(a){var b=[],c;for(c in g_shareeautopushes)for(var e in g_shareeautopushes[c]){var d=g_shareeautopushes[c][e],f="";if(have_nplastpass()&&typeof g_nplastpass.xCryptoRSADecrypt=="function"){f=g_nplastpass.xCryptoRSADecrypt(a,d.sharekeyhexenc);f=AES.hex2bin(f)}else{f=new RSAKey;if(!parse_private_key(f,a)){console_error("Private key could not be parsed while auto accepting shares");return}f=f.decrypt(d.sharekeyhexenc)}if(!(f==""||f==null)){d=reencryptShareeAutoPushes(f,
d,c);if(d!=null){if(typeof b[c]=="undefined")b[c]=[];b[c].push(d)}}}a="cmd="+LP.en("updateautoshareepushes")+"&from="+LP.en("ffplugin");f=e=0;for(c in b){++e;for(var h in b[c]){var g="&share"+f;d=b[c][h];for(var i in d)a+=g+i+"="+LP.en(d[i]);++f}}a+="&numupdates="+LP.en(f);if(f>0){lplastgetaccounts=0;lpMakeRequest(base_url+"showacceptshare.php",a,rsa_acceptshareeautopushesresponse)}else lpdbg("sharing","lprsa_acceptshareeautopushes : no shareeautopushes so not issuing server request")}
function rsa_acceptshareeautopushesresponse(a){if(a.readyState==4){lpdbg("sharing","lprsa_acceptshareeautopushesresponse : received response from server");if(a.status!=200)lpReportError("lprsa_acceptshareeautopushesresponse : request failed status="+a.status);else if(a.responseXML==null||a.responseXML.documentElement==null)lpReportError("lprsa_acceptshareeautopushesresponse : request failed xml invalid A text="+a.responseText);else{var b=a.responseXML.documentElement.getElementsByTagName("ok");!b||
b.length==0?lpReportError("lprsa_acceptshareeautopushesresponse : request failed xml invalid B text="+a.responseText):get_accts()}}}
function rsa_shareeautopushesresponse(a,b){if(a.readyState!=4||a.status!=200||a.responseXML==null||a.responseXML.documentElement==null)return false;if(typeof b=="undefined"||b==null)return false;var c=(new Date).getTime(),e=b.url,d=b.aid,f=b.handler,h=b.param,g=b.postdata;d=typeof g_sites[d]!="undefined"?g_sites[d]:typeof g_securenotes[d]!="undefined"?g_securenotes[d]:null;if(d==null){d={};d.name="";d.group="";d.username="";d.password="";d.extra=""}g=createShareeAutoPushesResponse(a,b,d);if(g==false)return false;
c=((new Date).getTime()-c)/1E3;lpdbg("sharing","Finished RSA encryption. Total time taken = "+c+" seconds");lpdbg("sharing","Reissuing request to "+e+" with postdata="+g);lplastgetaccounts=0;lpMakeRequest(e,g,f,null,h);return true}
function lprsa_encryptdata(a,b){var c=null;if(have_nplastpass()&&typeof g_nplastpass.xCryptoRSAEncrypt=="function")c=g_nplastpass.xCryptoRSAEncrypt(a,b);else{c=new RSAKey;if(!parse_public_key(c,a)){console_error("Private key could not be parsed while auto accepting shares");return false}c=c.encrypt(AES.hex2bin(b))}if(b!=""&&(c==null||c=="")){lpReportError("lprsa_encryptdata : Failed to rsaencrypt data using publickeyhex="+a);return false}return c}
function lprsa_rsadecrypt(a){if(lp_rsaprivatekeyhex=="")return null;if(!have_nplastpass())return null;if(typeof g_nplastpass.xCryptoRSADecrypt!="function")return null;return g_nplastpass.xCryptoRSADecrypt(lp_rsaprivatekeyhex,a)}
function lprsa_encryptmultiple(a){if(!have_nplastpass())return null;if(typeof g_nplastpass.xCryptoRSAEncrypt!="function")return null;a=JSON.parse(a);for(var b=0;b<a.length;++b){if(typeof a[b].valuehex=="undefined"||typeof a[b].publickeyhex=="undefined"||a[b].publickeyhex=="")return null;a[b].valuehexenc=g_nplastpass.xCryptoRSAEncrypt(a[b].publickeyhex,a[b].valuehex);if(""==a[b].valuehexenc||null==a[b].valuehexenc)return null}return JSON.stringify(a)};
