var data=null,existing=null,origusername=null,origpassword=null,attachnum=0,attaches=[],removedattach=[],g_eye_show=!0,g_eyeimgid=null,event_handlers={};function fix_event_handlers(){lpdbg("site","fixing event handlers");for(var b in event_handlers){lpdbg("site","setting event handler for "+b);var c=document.getElementById("fields").contentWindow.document.getElementById(b);c?(c.onclick=event_handlers[b],lpdbg("site","set event handler for "+b)):lpdbg("site","could not find "+b)}}
function onLoad(b){clearData();if(b){var c=getBG();data=c.g_site_data;c.g_site_data=null;c.g_generatedpw&&(document.getElementById("pwprotect").style.visibility="hidden",document.getElementById("pwprotectlabel").style.visibility="hidden");if((existing=data&&"undefined"!=typeof get_record_id(data)&&get_record_id(data)&&""!=get_record_id(data)&&"0"!=get_record_id(data))&&!c.LPISLOC&&c.g_showhistorylinks)document.getElementById("usernamehistory").style.display="",document.getElementById("passwordhistory").style.display=
"";if(data){b=issharedfolder(c.g_shares,data.group);var d=!1==b?c.g_local_key:b.sharekey;"http://sn"==data.url&&c.loglogin(get_record_id(data));b=!1;if(is_application(data)){document.getElementById("usernamehistory").style.display="none";document.getElementById("passwordhistory").style.display="none";document.getElementById("urltext").innerHTML=gs("Application:");document.getElementById("url").value=data.appname;for(var a=0,k=0,e=0;e<data.fields.length;e++)if(""==data.fields[e].type){if(1<++a)break}else if("password"==
data.fields[e].type&&1<++k)break;if(1!=a||1!=k)b=!0}else if(a=AES._utf8_decode(data.url),existing||!(0<=a.indexOf("homelocal")))document.getElementById("url").value=a;event_handlers={};data.editfields?(document.title=is_application(data)?gs("Edit Application Fields"):gs("Edit Site Fields"),document.getElementById("urlrow").style.display="none",document.getElementById("namegrouprow").style.display="none",document.getElementById("usernamepasswordrow").style.display="none",document.getElementById("notesrow1").style.display=
"none",document.getElementById("notesrow2").style.display="none",document.getElementById("checkboxrow1").style.display="none",document.getElementById("checkboxrow2").style.display="none",document.getElementById("fieldsrow2").style.display="",document.getElementById("fields").contentWindow.document.body.innerHTML=getFieldsHTML(d)):data.save_all||b?(document.getElementById("usernamepasswordrow").style.display="none",document.getElementById("fieldsrow1").style.display="",document.getElementById("fieldsrow2").style.display=
"",existing?(document.title=is_application(data)?gs("Edit Application"):gs("Edit Site"),document.getElementById("fields").contentWindow.document.body.innerHTML=getFieldsHTML(d)):(document.title=gs("Add Site"),document.getElementById("fields").contentWindow.document.body.innerHTML=getDataHTML())):data.sn?(document.title=existing?gs("Edit Secure Note"):gs("Add Secure Note"),document.getElementById("usernamepasswordrow").style.display="none",document.getElementById("urlrow").style.display="none"):existing?
(is_application(data)?(document.title=gs("Edit Application"),document.getElementById("username").value=getusernamefromacct(data),document.getElementById("password").value=getpasswordfromacct(data),origusername=c.lpmenc(document.getElementById("username").value,!0,d),origpassword=c.lpmenc(document.getElementById("password").value,!0,d)):(document.title=gs("Edit Site"),document.getElementById("username").value=data.unencryptedUsername,document.getElementById("password").value=c.lpmdec(data.password,
!0,d),origusername=data.username,origpassword=data.password),document.getElementById("editfields").style.display=""):(document.title=gs("Add Site"),document.getElementById("username").value=data.username,document.getElementById("password").value=data.password);fix_event_handlers();!existing&&("undefined"!=typeof data.addsite&&-1==AES._utf8_decode(data.url).indexOf("homelocal"))&&(document.getElementById("name").value=c.getname_url(data.url));existing?(document.getElementById("name").value=data.name,
document.getElementById("group").value=data.group,document.getElementById("notes").value=c.lpmdec(data.extra,!0,d),document.getElementById("fav").checked="1"==data.fav,document.getElementById("pwprotect").checked=data.pwprotect,document.getElementById("autologin").checked=data.autologin&&"0"!=data.autologin,is_application(data)?document.getElementById("never_autofill_td").style.visibility="hidden":document.getElementById("never_autofill").checked=data.never_autofill):data.sn&&(document.getElementById("group").value=
gs("Secure Notes"));1==data.sn&&(document.getElementById("checkboxrow1").style.display="none",document.getElementById("autologingrp").style.visibility="hidden")}existing&&!data.editfields?(document.getElementById("del").style.display="",b=get_record(get_record_id(data)),document.getElementById("share").style.display=!c.LPISLOC&&!b.genpw&&("undefined"==typeof b.sharedfromaid||null==b.sharedfromaid||""==b.sharedfromaid||"0"==b.sharedfromaid||"null"==b.sharedfromaid)&&"undefined"==typeof b.sharefolderid&&
!is_application(b)?"":"none"):(document.getElementById("del").style.display="none",document.getElementById("share").style.display="none");b=[];for(aid in c.g_sites)c.check_ident_aid(aid)&&(a=c.g_sites[aid].group,""!=a&&!lp_in_array(a,b)&&(b[b.length]=a));for(aid in c.g_securenotes)c.check_ident_aid(aid)&&(a=c.g_securenotes[aid].group,""!=a&&!lp_in_array(a,b)&&(b[b.length]=a));for(aid in c.g_applications)c.check_ident_appaid(aid)&&(a=c.g_applications[aid].group,""!=a&&!lp_in_array(a,b)&&(b[b.length]=
a));b.sort(function(a,b){return a.toLowerCase()<b.toLowerCase()?-1:1});create_combo("group",b);if(!existing&&data&&!data.save_all&&!data.noreplace){a=c.getsites(lp_gettld_url(data.url),!0);b=[];for(e in a)b[b.length]=e;b.sort(function(a,b){return c.g_sites[a].name.toLowerCase()<c.g_sites[b].name.toLowerCase()?-1:1});a=document.getElementById("replaceexistingsiteaid");for(e=0;e<b.length;e++)k=c.g_sites[b[e]].name,typeof c.g_sites[b[e]].useusername&&""!=c.g_sites[b[e]].useusername&&(k+=" ("+c.g_sites[b[e]].useusername+
")"),a.options[a.options.length]=new Option(k,b[e]);if(1<a.options.length)for(e=1;4>=e;e++)document.getElementById("addreplacerow"+e).style.display=""}update_password_meter("",document.getElementById("password").value);buildSecureNotes();onResize();setup_eye_events(document);setTimeout(function(){decryptThumbnails(d)},0)}else get_data("site",function(){onLoad(!0)})}
function decryptThumbnails(b){try{if("undefined"!=typeof data&&(null!==data&&1==data.sn)&&(document.getElementById("lpaddattach").style.display="","undefined"!=typeof data.attachpresent&&"1"==data.attachpresent)){getBG();for(var c in data.attaches)data.attaches.hasOwnProperty(c)&&addThumbnail(data.attaches[c].id,data.attaches[c].mimetype,data.attaches[c].bytes,null,data.attachkey,b)}}catch(d){console.error(d)}}
function buildSecureNotes(){if("undefined"!=typeof data&&null!==data&&"undefined"!=typeof data.sn&&1==data.sn){document.getElementById("notesrow0").style.display="";document.getElementById("notesrow1").style.display="none";document.getElementById("attachtable").style.width="200px";document.getElementById("group_container").style.width="270px";document.getElementById("group").style.width="auto";var b=document.getElementById("notestype").val,c=[],d;for(d in sntemplates){var a="undefined"!=typeof sntemplateicons[d]?
sntemplateicons[d]:geticonurl("sn");c[c.length]={label:gs(d),image:a,value:d}}create_combo("notestype",c);existing&&(b=getNoteValue("NoteType",document.getElementById("notes").value));if(!b||"undefined"==typeof sntemplates[b])b="Generic";init_attachment_action_menu();document.getElementById("autologingrp").setAttribute("colspan","0");c=document.getElementById("pwaginggrp");null!=c&&c.setAttribute("colspan","2");buildForm(b);onResize()}else document.getElementById("attachtable").style.width="0px"}
function buildForm(b){var c=document.getElementById("notestype");c.value=gs(b);c.val=b;var d="undefined"!=typeof sntemplateicons[b]?sntemplateicons[b]:geticonurl("sn");c.style.background="url("+d+") no-repeat 2px 2px";document.getElementById("notesrow2").style.display="Generic"==b?"":"none";document.getElementById("notesrow3").style.display="Generic"==b?"none":"";document.getElementById("notestype").disabled=existing?!0:!1;if("Generic"!=b){for(c=document.getElementById("dynamicnotes");c.hasChildNodes()&&
0<c.childNodes.length;)c.removeChild(c.firstChild);d=sntemplates[b];b=document.createElement("table");b.style.width="100%";b.style.borderSpacing="0px";for(var a in d){var k=document.createElement("tr"),e=document.createElement("td");e.style.whiteSpace="nowrap";var g=document.createElement("td");g.style.width="100%";var f=document.createTextNode(gsproper(a)+":");e.appendChild(f);f=null;if("text"==d[a])f=document.createElement("input"),f.type="text",f.id="note_"+a,f.style.width="100%",f.style.fontFamily=
"Courier",existing&&(f.value=getNoteValue(a,document.getElementById("notes").value));else if("date"==d[a]||"datemoyr"==d[a]){f=document.createElement("span");f.style.width="100%";var j=document.createElement("select");j.id="note_"+a+"_mo";j.style.width="auto";var h="January February March April May June July August September October November December".split(" "),n;for(n in h)j.options[j.options.length]=new Option(gs(h[n]),h[n]);var p=null;if(existing&&((p=getNoteValue(a,document.getElementById("notes").value))&&
(p=p.split(",")),p&&0<p.length))for(var u in h)if(h[u]==p[0]||gs(h[u])==p[0]){j.value=h[u];break}f.appendChild(j);if("date"==d[a]){j=document.createElement("select");j.id="note_"+a+"_day";for(n=1;31>=n;n++)j.options[j.options.length]=new Option(n,n);p&&1<p.length&&(j.value=p[1]);f.appendChild(j)}j=document.createElement("input");j.type="text";j.maxLength=4;j.size=4;j.id="note_"+a+"_yr";h="date"==d[a]?2:1;p&&p.length>h&&(j.value=p[h]);f.appendChild(j)}else if("textarea"==d[a])e.style.verticalAlign=
"top",f=document.createElement("textarea"),f.cols=30,f.rows=7,f.id="note_"+a,f.style.width="100%",existing&&(f.value=getNoteValue(a,document.getElementById("notes").value,!0));else continue;g.appendChild(f);k.appendChild(e);k.appendChild(g);b.appendChild(k)}a=document.createElement("fieldset");a.appendChild(b);c.appendChild(a)}}
function onResize(){if("undefined"!=typeof data&&null!=data&&1==data.sn){var b=document.getElementById("thetable"),c=document.getElementById("maintable"),d=document.getElementById("notes");d.style.height=window.innerHeight-c.offsetTop-(b.clientHeight-d.clientHeight)-20}}
function fix_addreplace(){document.getElementById("addnewsite").checked?(document.getElementById("url").disabled=!1,document.getElementById("name").disabled=!1,document.getElementById("group").disabled=!1,document.getElementById("username").disabled=!1,document.getElementById("password").disabled=!1,document.getElementById("notes").disabled=!1,document.getElementById("fav").disabled=!1,document.getElementById("never_autofill").disabled=!1,document.getElementById("pwprotect").disabled=!1,document.getElementById("autologin").disabled=
!1,document.getElementById("replaceexistingsiteaid").disabled=!0):document.getElementById("replaceexistingsite").checked&&(document.getElementById("url").disabled=!0,document.getElementById("name").disabled=!0,document.getElementById("group").disabled=!0,document.getElementById("username").disabled=!0,document.getElementById("password").disabled=!0,document.getElementById("notes").disabled=!0,document.getElementById("fav").disabled=!0,document.getElementById("never_autofill").disabled=!0,document.getElementById("pwprotect").disabled=
!0,document.getElementById("autologin").disabled=!0,document.getElementById("replaceexistingsiteaid").disabled=!1)}
function getSecureNoteFromFields(){if("undefined"!=typeof data&&1==data.sn){var b=document.getElementById("notestype").val;if("Generic"==b||"none"==document.getElementById("notesrow0").style.display)return document.getElementById("notes").value;var c="NoteType:"+b+"\n",d;for(d in sntemplates[b])"text"==sntemplates[b][d]?c+=d+":"+document.getElementById("note_"+d).value+"\n":"date"==sntemplates[b][d]||"datemoyr"==sntemplates[b][d]?(c+=d+":"+document.getElementById("note_"+d+"_mo").value,"date"==sntemplates[b][d]&&
(c+=","+document.getElementById("note_"+d+"_day").value),c+=","+document.getElementById("note_"+d+"_yr").value+"\n"):"textarea"==sntemplates[b][d]&&(c+=d+":"+document.getElementById("note_"+d).value+"\n");return c}return document.getElementById("notes").value}function get_decrypted_attachdata(b){for(var c in g_encatt)if("undefined"!=typeof g_encatt[c].id&&g_encatt[c].id==b)return g_encatt[c].data;return""}
function dosave(b,c){var d=document.getElementById("replaceexistingsite").checked;if(d&&0==document.getElementById("replaceexistingsiteaid").selectedIndex)alert(gs("Please Make a Selection"));else{var a=getBG();if(a.lploggedin)if(data.editfields){var k=issharedfolder(a.g_shares,data.group);if(checkreadonly(k)){var e=!1==k?a.g_local_key:k.sharekey;if(is_application(data)){var g=get_record(get_record_id(data));g.last_touch=lp_get_gmt_timestamp();for(var f in g.fields){var d=g.fields[f],j=document.getElementById("fields").contentWindow.document.getElementById(d.htmlid);
j&&(d.value=a.lpmenc(j.value,!0,e))}var h="appaid="+a.en(g.appaid);for(f in g.fields)d=g.fields[f],h+="&fieldid"+f+"="+a.en(d.id)+"&fieldtype"+f+"="+a.en(d.type)+"&fieldvalue"+f+"="+a.en(crypto_btoa(d.value));h+=!1==k?"":"&sharedfolderid="+a.en(k.id);(g_issafari||g_isopera||g_ismaxthon)&&a.update_site(get_record_id(data));a.increment_local_accts_version();a.rewritelocalfile();a.saveSite(h,g)}else checkFieldsForUpdates(e);getBG().close_editfieldsopener();setTimeout(function(){getBG().closecurrenttab("site.html")},
0)}}else{var g=punycode.URLToASCII(document.getElementById("url").value),n=document.getElementById("name").value,h=document.getElementById("group").value,p=document.getElementById("username").value,u=document.getElementById("password").value,m=getSecureNoteFromFields(),j=document.getElementById("fav").checked,s=document.getElementById("never_autofill").checked,v=document.getElementById("pwprotect").checked,q=document.getElementById("autologin").checked,k=issharedfolder(a.g_shares,h);if(checkreadonly(k)){var x=
!1;if(existing&&h!=data.group){if(x=issharedfolder(a.g_shares,data.group),!checkmove(k,x))return}else existing&&(x=k);e=existing?!1==x?a.g_local_key:x.sharekey:!1==k?a.g_local_key:k.sharekey;if(d)var l=a.g_sites[document.getElementById("replaceexistingsiteaid").value],n=l.name,h=l.group,k=issharedfolder(a.g_shares,h),e=!1==k?a.g_local_key:k.sharekey,m=a.lpmdec(l.extra,!0,e),j="1"==l.fav,s=l.never_autofill,v=l.pwprotect,q=l.autologin;if(""==n)alert(gs("You must enter a name."));else{if(45E3<m.length)if(confirm(gs("The notes field contains too much data.  You may store a maximum of 45,000 characters per note.\n\nWould you like us to truncate the note for you?  You will lose some of your data.")))m=
m.substring(0,45E3);else return;if(existing&&h!=data.group&&(k||x)){var r=[get_record_id(data)],t=[];t[get_record_id(data)]=h;if(!a.moveIntoSharedFolder(k,x,r,t,!1,!0))return}if(existing&&is_application(data)){g=get_record(get_record_id(data));g.last_touch=lp_get_gmt_timestamp();s=getusernamefromacct(g);v=getpasswordfromacct(g);for(f in g.fields)if(d=g.fields[f],""==document.getElementById("fieldsrow2").style.display){if(j=document.getElementById("fields").contentWindow.document.getElementById(d.htmlid))d.value=
a.lpmenc(j.value,!0,e)}else""==d.type&&a.lpmdec_acct(d.value,!0,g,a.g_shares)==s?d.value=a.lpmenc(document.getElementById("username").value,!0,e):"password"==d.type&&a.lpmdec_acct(d.value,!0,g,a.g_shares)==v&&(d.value=a.lpmenc(document.getElementById("password").value,!0,e));g.name=document.getElementById("name").value;g.group=document.getElementById("group").value;g.appname=document.getElementById("url").value;d=getSecureNoteFromFields();d!=a.lpmdec(g.extra,!0,e)&&(g.extra=lpmenc(d,!0,e));g.fav=
document.getElementById("fav").checked?"1":"0";g.pwprotect=document.getElementById("pwprotect").checked;g.autologin=document.getElementById("autologin").checked?"1":"0";var w=g.group;k&&(g.sharefolderid=k.id,w=w.substr(k.decsharename.length+1));if(h!=data.group&&(k||x))r=[get_record_id(data)],t=[],t[get_record_id(data)]=g.group,a.moveIntoSharedFolder(k,x,r,t,!1,!1,!0);else{h="ajax=1&extjs=1&cmd=updatelpaa&name="+a.en(a.lpenc(g.name,e))+"&grouping="+a.en(a.lpenc(w,e))+"&appname="+a.en(g.appname)+"&extra="+
a.en(crypto_btoa(g.extra))+"&appaid="+a.en(g.appaid);"1"==g.fav&&(h+="&fav=on");g.pwprotect&&(h+="&pwprotect=on");"1"==g.autologin&&(h+="&autologin=on");for(f in g.fields)d=g.fields[f],h+="&fieldid"+f+"="+a.en(d.id)+"&fieldtype"+f+"="+a.en(d.type)+"&fieldvalue"+f+"="+a.en(crypto_btoa(d.value));h+=!1==k?"":"&sharedfolderid="+a.en(k.id);(g_issafari||g_isopera||g_ismaxthon)&&a.update_site(get_record_id(data));a.increment_local_accts_version();a.rewritelocalfile();a.saveSite(h,g)}setTimeout(function(){getBG().closecurrenttab("site.html")},
0)}else{l=existing?data.sn?a.g_securenotes[get_record_id(data)]:a.g_sites[get_record_id(data)]:a.createNewAcct();w=!1;for(f in attaches)attaches.hasOwnProperty(f)&&"undefined"!=typeof attaches[f]&&(w=!0);if(w&&!c){"undefined"==typeof l.attachkey||""==l.attachkey?(r=SHA256(lpCreatePass(32,1,1,1,1,1,1,1)),g_attachkey=a.lpenc(r,e)):g_attachkey=l.attachkey;r=[];for(f in attaches)attaches.hasOwnProperty(f)&&"undefined"!=typeof attaches[f]&&(r[r.length]={id:attaches[f].id,bytes:attaches[f].bytes});if(r.length)if(t=
AES.hex2bin(a.lpdec(g_attachkey,e)),r=a.fastEncryptAttachments(t,r),a.g_ischrome)g_encatt=r;else return}var y=lp_gettld_url(AES._utf8_encode(g));if(existing&&l.tld!=y&&!b&&a.g_prompts.view_pw_prompt)a.security_prompt(function(){dosave(1)});else{existing&&!l.sn&&a.fix_tlds(l.tld,y,get_record_id(data));l.genpw=!1;l.name=n;l.group=h;"http://sn"==g?(l.url=g,l.sn=1):l.url=AES._utf8_encode(g);l.tld=y;l.unencryptedUsername=p;p!=a.lpmdec(l.username,!0,e)&&(l.username=a.lpmenc(p,!0,e));u!=a.lpmdec(l.password,
!0,e)&&(l.password=a.lpmenc(u,!0,e));m!=a.lpmdec(l.extra,!0,e)&&(l.extra=a.lpmenc(m,!0,e));l.fav=j?"1":"0";l.autologin=q;l.never_autofill=s;l.pwprotect=v;existing||(l.aid="0");!1!=k&&(l.sharefolderid=k.id,0==k.give&&(l.sharedfromaid=1));r="";t=[];if(w){if("undefined"==typeof l.attachkey||""==l.attachkey)l.attachkey=g_attachkey,r+="&attachkey="+a.en(l.attachkey);l.attachpresent="1";l.retrieveattach=1;w=0;for(f in attaches)attaches.hasOwnProperty(f)&&"undefined"!=typeof attaches[f]&&(r+="&mimetype"+
w+"="+a.en(attaches[f].mimetype),r+="&attachid"+w+"="+a.en(attaches[f].id),r+="&attachbytes"+w+"="+a.en(get_decrypted_attachdata(attaches[f].id)),"undefined"==typeof t.add&&(t.add=[]),t.add[t.add.length]=existing?{id:l.aid+"-"+attaches[f].id,mimetype:attaches[f].mimetype,parent:l.aid}:{id:attaches[f].id,mimetype:attaches[f].mimetype},w++)}if(0<removedattach.length){l.retrieveattach=1;for(f=0;f<removedattach.length;f++)r+="&rmattach"+f+"="+a.en(removedattach[f]),"undefined"==typeof t.remove&&(t.remove=
[]),t.remove[t.remove.length]=removedattach[f]}w=h;k&&(w=h.substr(k.decsharename.length+1));if(existing){if(g!=data.url||n!=data.name||h!=data.group||p!=data.unencryptedUsername||u!=a.lpmdec(data.password,!0,e)||m!=a.lpmdec(data.extra,!0,e)||j!=("1"==data.fav)||s!=data.never_autofill||v!=data.pwprotect||q!=data.autologin||0<attaches.length||0<removedattach.length){l.sn?a.g_securenotes[l.aid]=l:a.g_sites[l.aid]=l;for(f in l.fields)if(l.fields.hasOwnProperty(f)&&(d=l.fields[f],is_encrypted_field(d.type)&&
(null!=origpassword&&""!=origpassword&&null!=d.value&&""!=d.value&&a.lpmdec_acct(d.value,!0,l,a.g_shares)==a.lpmdec_acct(origpassword,!0,l,a.g_shares))&&"password"==d.type&&(d.value=l.password),is_encrypted_field(d.type)&&(null!=origusername&&""!=origusername&&null!=d.value&&""!=d.value&&a.lpmdec_acct(d.value,!0,l,a.g_shares)==a.lpmdec_acct(origusername,!0,l,a.g_shares))&&("text"==d.type||"email"==d.type||"tel"==d.type||"url"==d.type)))d.value=l.username;if(h!=data.group&&(k||x)){r=[get_record_id(data)];
t=[];t[get_record_id(data)]=l.group;a.moveIntoSharedFolder(k,x,r,t,!1,!1,!0);setTimeout(function(){getBG().closecurrenttab("site.html")},0);return}(g_issafari||g_isopera||g_ismaxthon)&&a.update_site(get_record_id(data));a.applyattacharraychanges(t);a.increment_local_accts_version();a.rewritelocalfile();h="ajax=1&extjs=1&name="+a.en(a.lpenc(n,e))+"&url="+a.en(AES.url2hex(g))+"&grouping="+a.en(a.lpenc(w,e))+"&username="+a.en(crypto_btoa(l.username))+"&password="+a.en(crypto_btoa(l.password))+"&extra="+
a.en(crypto_btoa(l.extra))+"&openid_url=&aid="+a.en(get_record_id(data))+"&basic_auth=0&isbookmark=0&localupdate=1";h=h+(v?"&pwprotect=on":"")+(s?"&never_autofill=on":"");h+=q?"&autologin=on":"";h+=j?"&fav=on":"";h+=!1==k?"":"&sharedfolderid="+a.en(k.id);h+=r;l.attacharraychanges=t;l.newvalues=[];a.saveSite(h,l);k=a.getsites(y,!0);u!=a.lpmdec(data.password,!0,e)&&1<array_length(k)&&a.openLinkedSites(u,y)}data.save_all&&checkFieldsForUpdates(e)}else l.fields=[],f=[],h=updateAndEncryptData(a,l.username,
l.password,l.fields,l,f,e),h="name="+a.en(a.lpenc(n,e))+"&grouping="+a.en(a.lpenc(w,e))+"&data="+a.en(a.bin2hex(h))+"&extra="+a.en(a.lpenc(m,e))+(v?"&pwprotect=on":"")+(s?"&never_autofill=on":"")+(q?"&autologin=on":"")+(j?"&fav=on":""),h+="&extjs=1&localupdate=1",h+=!1==k?"":"&sharedfolderid="+a.en(k.id),"undefined"!=typeof data.realm&&(l.realm=a.lpmenc(data.realm,!0,e),l.basic_auth="1",h+="&basic_auth=1&realm="+a.en(a.lpenc(l.realm,e))),"http://sn"==g&&(e=getNoteValue("NoteType",m),h+=e&&""!=e?"&notetype="+
a.en(e):""),d&&(h+="&replacing=1"),h+=r,data.save_all?(l.save_all=!0,h+="&ajax=1&aid=0&save_all=1&url="+a.en(AES.url2hex(g))+"&openid_url=&username=&password=",l.newvalues=f,a.saveAllSite(h,l)):"undefined"!=typeof data.formdata?(h+="&ref="+a.en(AES.url2hex(g)),d&&(h+="&aid="+a.en(document.getElementById("replaceexistingsiteaid").value)),"undefined"!=typeof data.createacct&&(data.createacct&&"undefined"!=typeof data.username_field)&&(l.fields=[],h+="&createacct=1&username_field="+a.en(data.username_field)),
l.newvalues=f,a.saveSiteFromSubmit(h,l)):(h+="&ajax=1&aid=0&url="+a.en(AES.url2hex(g))+"&openid_url=&username="+a.en(crypto_btoa(l.username))+"&password="+a.en(crypto_btoa(l.password)),l.newvalues=f,l.attacharraychanges=t,a.saveSite(h,l));setTimeout(function(){getBG().closecurrenttab("site.html")},0)}}}}}else console_log("Not logged in!")}}
function checkFieldsForUpdates(b){var c=getBG(),d=document.getElementById("fields").contentWindow.document,a=!1,k;for(k in data.fields){var e=data.fields[k];if(is_encrypted_field(e.type)){var g=d.getElementById(e.htmlid);if(g&&"undefined"!=typeof g.value&&c.lpmdec(e.value,!0,b)!=g.value){var a=!0,f=c.lpmenc(g.value,!0,b);""!=e.value&&(""!=c.g_sites[get_record_id(data)].username&&e.value==c.g_sites[get_record_id(data)].username&&""!=g.value)&&(c.g_sites[get_record_id(data)].username=f,c.g_sites[get_record_id(data)].unencryptedUsername=
g.value);""!=e.value&&(""!=c.g_sites[get_record_id(data)].password&&e.value==c.g_sites[get_record_id(data)].password&&""!=g.value)&&(c.g_sites[get_record_id(data)].password=f);e.value=f}}else if("checkbox"==e.type||"radio"==e.type)g=e.checked,f=d.getElementById(e.htmlid)&&d.getElementById(e.htmlid).checked,g!=f&&(a=!0,e.checked=f);else if("select-one"==e.type&&e.faketype&&(g=d.getElementById(e.htmlid))&&"undefined"!=typeof g.value&&e.value!=g.value)a=!0,e.value=g.value}if(a){if(g_issafari||g_isopera||
g_ismaxthon)c.update_site(get_record_id(data)),c.update_fields(get_record_id(data),data.fields);c.increment_local_accts_version();c.rewritelocalfile();b="update=1&aid="+c.en(get_record_id(data))+"&urid=0";a="";g=[];for(k in data.fields)if(e=data.fields[k],f=data.editfields&&""==e.formname?"_"+e.name:"_"+e.formname+"_"+e.name,is_encrypted_field(e.type)){var j=d.getElementById(e.htmlid).value;g.push(j);j=crypto_btoa(e.value);a+=f+"="+c.en(j)+"&"}else"checkbox"==e.type?d.getElementById(e.htmlid).checked&&
(a+=f+"="+c.en(e.value)+"&"):"select-one"==e.type&&e.faketype&&(j=d.getElementById(e.htmlid).value,a+=f+"="+c.en(j)+"&");a+="&auto=1";d=issharedfolder(c.g_shares,data.group);a+=!1==d?"":"&sharedfolderid="+c.en(d.id);c.saveFields(b,a,{url:base_url+"fields.php?"+b,aid:data.aid,postdata:a,param:null,newvalues:g})}}
function updateAndEncryptData(b,c,d,a,k,e,g){for(var f="",j="undefined"!=typeof data.formdata?data.formdata.split("\n"):[],h=!1,n=0,p=0,u=0;u<j.length;u++){var m=j[u],m=m.split("\t");4!=m.length&&5!=m.length||("text"==m[3]||"email"==m[3]||"tel"==m[3]||"url"==m[3]?n++:"password"==m[3]&&p++)}0==n&&(2==p&&!data.save_all)&&(h=!0);for(u=0;u<j.length;u++)if(m=j[u],m=m.split("\t"),!(4!=m.length&&5!=m.length)){var n=data.save_all?decodeURIComponent(m[0]):"0",p=decodeURIComponent(m[1]),s=decodeURIComponent(m[2]),
v=getBG().lpmenc(s,!0,g),m=m[3];if("text"==m||"password"==m||"hidden"==m||"textarea"==m||"email"==m||"tel"==m||"url"==m){if("email"==m&&s==data.username&&(v=c),"tel"==m&&s==data.username&&(v=c),"url"==m&&s==data.username&&(v=c),"text"==m&&s==data.username&&(v=c),"password"==m&&h?(v=c,h=!1):"password"==m&&s==data.password&&(v=d),s=lpmdec(v,!0,g),e&&e.push(s),f+=n+"\t"+b.en(p)+"\t"+b.en(crypto_btoa(v))+"\t"+b.en(m)+"\n","hidden"!=m){var q=[];q.otherfield=data.save_all;q.name=p;q.type=m;q.value=v;q.checked=
!1;q.formname=data.save_all?n:"";q.urid="0";q.otherlogin="0";q.url="";a[a.length]=q}}else if("action"==m)f+=n+"\taction\t"+b.en(s)+"\taction\n",k.action=AES.url2hex(s);else if("method"==m)f+=n+"\tmethod\t"+b.en(s)+"\tmethod\n",k.method=s;else if(f+=n+"\t"+b.en(p)+"\t"+b.en(s)+"\t"+b.en(m)+"\n","checkbox"==m||"radio"==m||"select-one"==m)q=[],q.otherfield=data.save_all,q.name=p,q.type=m,"checkbox"==m||"radio"==m?(q.checked="-1"==s.substring(s.length-2),q.value=s.substring(0,s.length-2)):q.value=s,q.formname=
data.save_all?n:"",q.urid="0",q.otherlogin="0",q.url="",a[a.length]=q}return f}
function getDataHTML(){for(var b='<link rel="stylesheet" type="text/css" href="general.css">',c=data.formdata.split("\n"),d=0;d<c.length;d++){var a=c[d].split("\t");if(!(4!=a.length&&5!=a.length)){var k=data.save_all?decodeURIComponent(a[0]):"0",e=decodeURIComponent(a[1]),g=decodeURIComponent(a[2]),a=a[3],k=uniqid(k+"_"+e);if("text"==a||"password"==a||"email"==a||"tel"==a||"url"==a)b+=ofja(e)+' <input readonly id="'+ofja(k)+'" name="'+ofja(e)+'" type="'+ofja(a)+'" value="'+ofa(g)+'">',"password"==
a&&(event_handlers[k+"toggle"]=function(){parent.toggle_password(document.getElementById("fields").contentWindow.document.getElementById(this.id.substring(0,this.id.length-6)),this);return!1},b+=' <a id="'+ofja(k)+'toggle" href="#">'+gs("[Show]")+"</a>"),b+="<br>";else if("textarea"==a)b+=ofja(e)+' <textarea readonly name="'+ofja(e)+'">'+ofa(g)+"</textarea><br>";else if("select-one"==a)b+=ofja(e)+' <select name="'+ofja(e)+'"><option value="'+ofa(g)+'">'+ofa(g)+"</option></select><br>";else if("checkbox"==
a||"radio"==a)checked="-1"==g.substring(g.length-2)?" checked":"","radio"==a&&""==checked||(g=g.substring(0,g.length-2),b+='<input disabled type="'+ofja(a)+'" value="'+ofa(g)+'"'+checked+"> "+ofja(e)+"<br>")}}return b}function showaddfield(){var b=getBG(),b=issharedfolder(b.g_shares,data.group);checkreadonly(b)&&(b=document.getElementById("fields").contentWindow.document,b.getElementById("addfield").style.display="",b.getElementById("newname").focus())}
function doaddfield(){var b=getBG(),c=issharedfolder(b.g_shares,data.group);if(checkreadonly(c)){var d=document.getElementById("fields").contentWindow.document,a=d.getElementById("newname").value,k=d.getElementById("newtype").value,e=k;"select-one"==e&&(e="text");var g=d.getElementById("newformname")?d.getElementById("newformname").value:"";if(""==a)alert(gs("You must enter a name."));else{for(var f in data.fields)if(data.fields[f].name==a&&(data.editfields||data.fields[f].formname==g)){alert(gs("You must enter a unique name."));
return}f=uniqid(g+"_"+a);var j="";"text"==k||"password"==k||"select-one"==k||"email"==k||"tel"==k||"url"==k?(j+=ofja(a)+' <input id="'+ofja(f)+'" type="'+ofja(e)+'">',"password"==k&&(j+=' <a id="'+ofja(f)+'toggle" href="#">'+gs("[Show]")+"</a>")):"textarea"==k?j+=ofja(a)+' <textarea id="'+ofja(f)+'"></textarea>':"checkbox"==k&&(j+='<input type="'+ofja(k)+'" id="'+ofja(f)+'"> <label for="'+ofja(f)+'">'+ofja(a)+"</label>");var j=j+(' <a href="#" id="'+ofja(f)+'delete" data-lpname="'+ofja(a)+'">[&nbsp;-&nbsp;]</a>'),
h=d.createElement("div");h.id=f+"_div";h.innerHTML=j;d.body.appendChild(h);event_handlers={};"password"==k&&(event_handlers[f+"toggle"]=function(){parent.toggle_password(document.getElementById("fields").contentWindow.document.getElementById(this.id.substring(0,this.id.length-6)),this);return!1});event_handlers[f+"delete"]=function(){parent.delete_field(this.id.substring(0,this.id.length-6)+"_div",this.getAttribute("data-lpname"),"");return!1};lpdbg("site","1 added event handler for "+f+"delete");
fix_event_handlers();j={};j.otherfield=!data.editfields;j.name=a;j.type=k;"select-one"==k&&(j.faketype=e);j.value="";j.formname=g;j.checked=!1;j.urid="0";j.otherlogin="0";j.url="";j.htmlid=f;data.fields[data.fields.length]=j;(g_issafari||g_isopera||g_ismaxthon)&&b.update_fields(get_record_id(data),data.fields);b.increment_local_accts_version();b.rewritelocalfile();a="add=1&aid="+b.en(data.aid)+"&urid=0&name="+b.en(a)+"&type="+k;data.editfields||(a+="&formname="+b.en(g));a+="&auto=1";c=!1==c?"":"sharedfolderid="+
b.en(c.id);b.saveFields(a,c,{url:base_url+"fields.php?"+a,aid:data.aid,postdata:c,param:null,newvalues:[]});d.getElementById("newname").value="";d.getElementById("newtype").selectedIndex=0;d.getElementById("newformname")&&(d.getElementById("newformname").value="");d.getElementById("addfield").style.display="none"}}}
function getFieldsHTML(b){var c=getBG(),d='<link rel="stylesheet" type="text/css" href="general.css">';is_application(data)||(event_handlers.addfieldlink=function(){parent.showaddfield();return!1},event_handlers.doaddfield=function(){parent.doaddfield()},d+='<a href="#" id="addfieldlink">'+gs("Add Field")+'</a><br><div id="addfield" style="display: none;">'+gs("Name:")+' <input type="text" id="newname" value=""><br>'+gs("Type:")+' <select id="newtype"><option value="text">'+gs("Text")+'</option><option value="password">'+
gs("Password")+'</option><option value="select-one">'+gs("Select")+'</option><option value="checkbox">'+gs("Checkbox")+"</option></select><br>",data.editfields||(d+=gs("Form Name:")+' <input type="text" id="newformname" value=""><br>'),d+='<input type="button" value="'+gs("Add")+'" id="doaddfield"><br><br></div>');var a=[],k;for(k in data.fields){var e=data.fields[k],g=e.formname,f=is_application(data)?k:e.name,j=e.value?e.value:"",h=j,n=e.type,p=f+"_"+n+"_"+j;if("undefined"==typeof a[p]){a[p]=!0;
g=uniqid(g+"_"+f);e.htmlid=g;p="";if(is_application(data)&&""==n||"text"==n||"password"==n||"email"==n||"tel"==n||"url"==n)h=crypto_btoa(j),j=c.lpmdec(j,!0,b),p+=ofja(f)+' <input id="'+ofja(g)+'" type="'+ofja(n)+'" value="'+ofa(j)+'">',"password"==n&&(event_handlers[g+"toggle"]=function(){parent.toggle_password(document.getElementById("fields").contentWindow.document.getElementById(this.id.substring(0,this.id.length-6)),this);return!1},p+=' <a id="'+ofja(g)+'toggle" href="#">'+gs("[Show]")+"</a>");
else if("textarea"==n)h=crypto_btoa(j),j=c.lpmdec(j,!0,b),p+=ofja(f)+' <textarea id="'+ofja(g)+'">'+ofa(j)+"</textarea>";else if("select-one"==n)p+=ofja(f)+' <select id="'+ofja(g)+'"><option value="'+ofa(j)+'">'+ofa(j)+"</option></select>";else if("checkbox"==n||"radio"==n){e=e.checked?" checked":"";if("radio"==n&&""==e)continue;p+='<input type="'+ofja(n)+'" id="'+ofja(g)+'" '+e+'> <label for="'+ofja(g)+'">'+ofja(f)+"</label>"}else continue;is_application(data)||(event_handlers[g+"delete"]=function(){parent.delete_field(this.id.substring(0,
this.id.length-6)+"_div",this.getAttribute("data-lpname"),this.getAttribute("data-lporigval"));return!1},lpdbg("site","2 added event handler for "+g+"delete"),p+=' <a href="#" id="'+ofja(g)+'delete" data-lpname="'+ofja(f)+'" data-lporigval="'+ofja(h)+'">[&nbsp;-&nbsp;]</a>');d+='<div id="'+ofja(g)+'_div">'+p+"</div>"}}return d}
function delete_field(b,c,d){try{if(confirm(gs("Are you sure you would like to delete this field?"))){var a=getBG(),k=issharedfolder(a.g_shares,data.group);if(checkreadonly(k)){var e=document.getElementById("fields").contentWindow.document;if(e.getElementById(b)){e.getElementById(b).style.display="none";for(var g in data.fields)if(data.fields.hasOwnProperty(g)&&data.fields[g].name==c){var f=data.fields[g].value;is_encrypted_field(data.fields[g].type)&&(f=crypto_btoa(f));f==d&&data.fields.splice(g,
1)}(g_issafari||g_isopera||g_ismaxthon)&&a.update_fields(get_record_id(data),data.fields);a.increment_local_accts_version();a.rewritelocalfile();var j="delete=1&aid="+a.en(get_record_id(data))+"&urid=0&name="+a.en(c)+"&value="+a.en(d),j=j+"&auto=1",h=!1==k?"":"sharedfolderid="+a.en(k.id);a.saveFields(j,h,{url:base_url+"fields.php?"+j,aid:data.aid,postdata:h,param:null,newfields:[]})}else alert("Sorry, deletion of the field failed. Please re-save the site.")}}}catch(n){console_log("caught exception in delete_field: "+
n.message)}}function dodel(){getBG().deleteAid(get_record_id(data),window,!1,!1,function(){setTimeout(function(){getBG().closecurrenttab("site.html")},0)})}function doshare(){if(!check_for_changes()||confirm(gs("Are you sure you want to share this item?  Doing so will cause you to lose any changes you have made to this item!"))){var b=getBG();b.unlock_plug2web();b.openbaseurl("?ac=1&share="+b.en(get_record_id(data)));setTimeout(function(){window_close("site.html")},0)}}
function docancel(){setTimeout(function(){getBG().closecurrenttab("site.html")},0)}function show_history(b){if(!check_for_changes()||confirm(gs("Are you sure you want to view history?  Doing so will cause you to lose any changes you have made to this item!"))){var c=getBG();c.unlock_plug2web();c.openbaseurl("?ac=1&"+(b?"username":"password")+"history="+c.en(get_record_id(data)));setTimeout(function(){window_close("site.html")},0)}}var logged=!1;
function toggle_password(b,c){if("password"==b.type){if(existing){var d=getBG();if(null!=data.sharedfromaid&&""!=data.sharedfromaid&&"0"!=data.sharedfromaid&&"null"!=data.sharedfromaid){alert(gs("This is a shared site. You are not permitted to view the password."));return}if(d.g_prompts.view_pw_prompt){g_eye_show&&null!=c&&"undefined"!=typeof c.children[0]&&"undefined"!=typeof c.children[0].children[0]?d.security_prompt(function(){b.type="text";c.children[0].children[0].src=get_eye_src(b.type,"glow");
c.children[0].children[0].setAttribute("alt",gs("[Hide]"))}):d.security_prompt(function(){b.type="text";c.innerHTML=gs("[Hide]")});return}}existing&&!logged&&(d.loglogin(get_record_id(data)),logged=!0);b.type="text";g_eye_show&&null!=c&&"undefined"!=typeof c.children[0]&&"undefined"!=typeof c.children[0].children[0]?(c.children[0].children[0].src=get_eye_src(b.type,"glow"),c.children[0].children[0].setAttribute("alt",gs("[Hide]"))):c.innerHTML=gs("[Hide]")}else b.type="password",g_eye_show&&null!=
c&&"undefined"!=typeof c.children[0]&&"undefined"!=typeof c.children[0].children[0]?(c.children[0].children[0].src=get_eye_src(b.type),c.children[0].children[0].setAttribute("alt",gs("[Show]"))):c.innerHTML=gs("[Show]")}function gsproper(b){return gs(b+"proper")!=b+"proper"?gs(b+"proper"):gs(b)}
function check_for_changes(){var b=getBG(),c=document.getElementById("url").value,d=document.getElementById("name").value,a=document.getElementById("group").value,k=document.getElementById("username").value,e=document.getElementById("password").value,g=getSecureNoteFromFields(),f=document.getElementById("fav").checked,j=document.getElementById("never_autofill").checked,h=document.getElementById("pwprotect").checked,n=document.getElementById("autologin").checked,p=issharedfolder(b.g_shares,a),p=!1==
p?b.g_local_key:p.sharekey;return is_application(data)?c!=data.appname||d!=data.name||a!=data.group||k!=getusernamefromacct(data)||e!=getpasswordfromacct(data)||g!=b.lpmdec(data.extra,!0,p)||f!=("1"==data.fav)||h!=data.pwprotect||n!=("1"==data.autologin):c!=data.url||d!=data.name||a!=data.group||k!=data.unencryptedUsername||e!=b.lpmdec(data.password,!0,p)||g!=b.lpmdec(data.extra,!0,p)||f!=("1"==data.fav)||j!=data.never_autofill||h!=data.pwprotect||n!=data.autologin}
function doeditfields(){var b=getBG();if(!check_for_changes()||confirm(is_application(data)?gs("LoseChangesApp"):gs("LoseChanges"))){b.g_site_data=[];for(var c in data)b.g_site_data[c]=data[c];b.g_site_data.editfields=1;b.set_editfieldsopener(window);b.openURL(getchromeurl("site.html"),null,b.g_site_data)}}function showattach(b){getBG().showImageAttach(b.getAttribute("src"))}
function openattach(b){var c=b.getAttribute("filename")?b.getAttribute("filename"):"";getBG().openAttach(get_record_id(data),b.getAttribute("attachid"),c)}function addattach(){getBG().have_nplastpass()?(getBG().addAttach(),getBG().g_ischrome&&addattachcb()):confirm(gs("This feature requires the binary version of this browser extension.  Would you like to install it now?"))&&getBG().install_binary()}
function addThumbnail(b,c,d,a,k,e){var g=document.getElementById("attachtable"),f=document.createElement("tr");f.id=b;var j=document.createElement("td");j.style.height="80px";j.style.width="80px";var h=document.createElement("img");h.style.maxWidth="100%";h.style.maxHeight="100%";h.style.maxWidth="75px";h.style.maxHeight="75px";h.className="attachimg";j.style.textAlign="center";j.style.marginTop="auto";j.style.marginBottom="auto";g.appendChild(f);f.appendChild(j);j.appendChild(h);d&&0==c.indexOf("data:image")?
(h.setAttribute("attachid",b),k?getBG().fastDecryptAttachment(b,c,d,k,e,function(a){getBG().g_ischrome&&(h.setAttribute("src",c+";base64,"+a),h.addEventListener("click",function(){attachment_action_menu(this,showattach)}))}):(h.setAttribute("src",c+";base64,"+d),getBG().have_nplastpass()?h.addEventListener("click",function(){attachment_action_menu(this,showattach)}):h.addEventListener("click",function(){showattach(this)}))):(h.setAttribute("attachid",b),getBG().have_nplastpass()?h.addEventListener("click",
function(){attachment_action_menu(this,openattach)}):h.addEventListener("click",function(){openattach(this)}),0==c.indexOf("data:audio")?h.setAttribute("src","images/recording.png"):0==c.indexOf("other:doc")?h.setAttribute("src","images/word.png"):0==c.indexOf("other:xls")||0==c.indexOf("other:csv")?h.setAttribute("src","images/excel.png"):0==c.indexOf("other:ppt")?h.setAttribute("src","images/powerpoint.png"):0==c.indexOf("other:pdf")?h.setAttribute("src","images/pdf.png"):0==c.indexOf("other:txt")?
h.setAttribute("src","images/text.png"):h.setAttribute("src","images/generic.png"));a&&h.setAttribute("filename",a);d=get_extension_from_mimetype(c);0<d.length?h.setAttribute("alt",gs(d)+" "+gs("File")):h.setAttribute("alt",gs("File"));a=document.createElement("td");f.appendChild(a);f=document.createElement("table");f.style.width="25px";k=document.createElement("tr");e=document.createElement("td");g=document.createElement("span");g.className="attachx";g.setAttribute("attachid",b);g.addEventListener("click",
function(){rmattach(this)});g.innerHTML="&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";e.appendChild(g);b=document.createElement("tr");g=document.createElement("td");g.style.height="30px";g.style.width="25px";g.className="attach_extension";var j=check_filename_badchars(d),n=null;j==FILENAME_FRAGMENT_VALID?n=document.createTextNode("."+d):0==j.length||j==FILENAME_FRAGMENT_EMPTY||(n=document.createTextNode("."+gs(d)));n&&g.appendChild(n);f.appendChild(k);f.appendChild(b);k.appendChild(e);b.appendChild(g);a.appendChild(f);
attachnum++}function createAttachId(){for(;;){var b=Math.floor(99999*Math.random()),c;for(c in data.attaches)if(data.attaches.hasOwnProperty(c)&&data.attaches[c].id==get_record_id(data)+"-"+b)break;for(c=0;c<attaches.length&&!("undefined"!=typeof attaches[c]&&attaches[c].id==b);c++);return b}}
function rmattach(b){b=b.getAttribute("attachid");if(confirm(gs("Are you sure you would like to remove this attachment?"))){if("undefined"!=typeof data.attachpresent&&"1"==data.attachpresent)for(var c in data.attaches)data.attaches.hasOwnProperty(c)&&b==data.attaches[c].id&&(removedattach[removedattach.length]=b);delete attaches[b];delThumbnail(b)}}
function delThumbnail(b){for(var c=document.getElementById("attachtable"),d=0;d<c.children.length;d++)if(c.children[d].id==b){c.removeChild(c.children[d]);break}}
function attachment_action_doSave(){if(null!=open_attach_target){var b=open_attach_target.getAttribute("filename")?open_attach_target.getAttribute("filename"):"";getBG().exportAttachment(get_record_id(data),open_attach_target.getAttribute("attachid"),b)}else alarm("error, trying to save an attachment that does not exist");close_attach_list()}
function clearData(){for(var b=document.getElementsByTagName("input"),c=0;c<b.length;c++)"button"!=b[c].type&&(b[c].value="");b=document.getElementsByTagName("textarea");for(c=0;c<b.length;c++)b[c].value=""}function uniqid(b){b||(b="");return"a"+SHA256(b+"_"+(new Date).getTime()+"_"+Math.floor(100*Math.random()))}
function setup_eye_events(b){if(g_eye_show){var c=b.getElementById("passwordtoggle");b.getElementById("passwordtoggleimg").style.verticalAlign="bottom";c.addEventListener("mouseover",function(b){eye_over(b);return!1});c.addEventListener("mouseout",function(b){eye_out(b);return!1})}}function eye_over(b){if(!(null==b||null==b.target)){var c=document.getElementById("passwordtoggleimg"),d=document.getElementById("password");b.target==c&&(c.src=get_eye_src(d.type,"glow"))}}
function eye_out(b){if(!(null==b||null==b.target)){var c=document.getElementById("passwordtoggleimg"),d=document.getElementById("password");b.target==c&&(c.src=get_eye_src(d.type))}}function get_eye_src(b,c){return"password"==b?null!=c?"images/Eyerect40x26_glow.png":"images/Eyerect40x26.png":null!=c?"images/Eyerect40x26_never_glow.png":"images/Eyerect40x26_never.png"};
